### ISSUE TITLE
Bot commands not working

### ISSUE THREAD

**Issue by l0g4n1337** [BritishBenji/GiveawayBotButtons#1]
Hi, I have installed your bot on replit, unfortunately when I start the commands to create a giveaway I have problems setting the channel and the number of winners.

**Comment by BritishBenji** [comment]
Whilst I don't suggest running Discord bots on repl.it, I can't see any reasons that it shouldn't work on that site. 

Are you receiving any errors for this? Or is it simply just not accepting input?

If you could screenshot and send any response the bot gives, that would be very helpful to find the source of the issue

**Comment by BritishBenji** [comment]
Ahhhhhh, okay. After running !giveaway, you don't need to use a prefix anymore, it'll just take the text you input, for example:
```
!giveaway 
(bot replies)
Something to giveaway
(bot replies)
1
etc.
```

**Comment by l0g4n1337** [comment]
As I sad ... Im an Idiot xD
It works :D
![Discord_sDoiXkRSVT](https://user-images.githubusercontent.com/49865595/153710740-b3ab8bf8-918b-438c-9d1d-ea5e02043279.png)
