### ISSUE TITLE
Error coming 

### ISSUE THREAD

**Issue by GurjotSingh1105** [BritishBenji/GiveawayBotButtons#2]
Ig its a dpy error if you can fix please fix it

**Comment by Lightning-playZ** [comment]
> Ig its a dpy error if you can fix please fix it

![Uploading IMG_20220313_184443.jpg…]()

**Comment by BritishBenji** [comment]
Can you give any other info on this error? Your "image" is just a link back to this issue

**Comment by Lightning-playZ** [comment]
> Can you give any other info on this error? Your "image" is just a link back to this issue

Nvm i forgot something btw can you add more features like end,reroll etc

**Comment by BritishBenji** [comment]
I'll have a look into it and see what I can add in the next few weeks when I have some time :)
